// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxYgPqaofPGHmfibwOeXEIvQaNhfbAo_k',
    appId: '1:811040901579:android:f356a3c35ae6d0ad35ce4e',
    messagingSenderId: '811040901579',
    projectId: 'firebase-sportsbook-by-vivarob',
    databaseURL: 'https://fir-sportsbook-by-vivarob.firebaseio.com',
    storageBucket: 'firebase-sportsbook-by-vivarob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhQDmnXo3VFyr_nu1SoCVLkCThYRfLqU',
    appId: '1:811040901579:ios:6e3ae3c3e1a32a1c35ce4e',
    messagingSenderId: '811040901579',
    projectId: 'firebase-sportsbook-by-vivarob',
    databaseURL: 'https://fir-sportsbook-by-vivarob.firebaseio.com',
    storageBucket: 'firebase-sportsbook-by-vivarob.appspot.com',
    androidClientId: '811040901579-5f0fer2bb4kopq4v7uf9k2oa8nihcjn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmFlutterApplication',
  );
}
